apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: slack-webhook
    creationPolicy: Owner
  data:
  - secretKey: webhook-url
    remoteRef:
      key: cairn/slack
      property: webhook-url
